package org.minhtrinh.eventease251.repository;

import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.minhtrinh.eventease251.dto.CreateEventRequest;
import org.minhtrinh.eventease251.dto.SessionRequest;
import org.minhtrinh.eventease251.dto.TicketCategoryRequest;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.support.GeneratedKeyHolder;
import org.springframework.jdbc.support.KeyHolder;
import org.springframework.stereotype.Repository;
import org.springframework.transaction.annotation.Transactional;

import java.sql.PreparedStatement;
import java.sql.Statement;
import java.sql.Timestamp;
import java.time.LocalDateTime;

@Repository
@RequiredArgsConstructor
@Slf4j
public class EventRepositoryCustomImpl implements EventRepositoryCustom {

    private final JdbcTemplate jdbcTemplate;

    @Override
    @Transactional
    public Long createEvent(CreateEventRequest request, Long organizerId) {
        log.info("Creating event with title: {} for organizer: {}", request.getTitle(), organizerId);
        
        // 1. Calculate overall event start and end times from sessions
        LocalDateTime eventStartTime = request.getSessions().stream()
                .map(SessionRequest::getStartDateTime)
                .min(LocalDateTime::compareTo)
                .orElse(LocalDateTime.now());
        
        LocalDateTime eventEndTime = request.getSessions().stream()
                .map(SessionRequest::getEndDateTime)
                .max(LocalDateTime::compareTo)
                .orElse(LocalDateTime.now().plusHours(1));
        
        // 2. Insert Event
        String eventSql = "INSERT INTO event (title, general_introduction, event_status, organizer_id, " +
                         "start_date_time, end_date_time, timestamp, poster_url) " +
                         "VALUES (?, ?, ?, ?, ?, ?, ?, ?)";
        
        KeyHolder eventKeyHolder = new GeneratedKeyHolder();
        
        jdbcTemplate.update(connection -> {
            PreparedStatement ps = connection.prepareStatement(eventSql, Statement.RETURN_GENERATED_KEYS);
            ps.setString(1, request.getTitle());
            ps.setString(2, request.getDescription());
            ps.setString(3, "COMING_SOON"); // Publish immediately
            ps.setLong(4, organizerId);
            ps.setTimestamp(5, Timestamp.valueOf(eventStartTime));
            ps.setTimestamp(6, Timestamp.valueOf(eventEndTime));
            ps.setTimestamp(7, Timestamp.valueOf(LocalDateTime.now()));
            ps.setString(8, request.getPosterUrl());
            return ps;
        }, eventKeyHolder);
        
        Long eventId = eventKeyHolder.getKey().longValue();
        log.info("Event created with ID: {}", eventId);
        
        // 3. Insert Event Regulations (if any)
        if (request.getRegulations() != null && !request.getRegulations().isEmpty()) {
            String regulationSql = "INSERT INTO event_regulation (event_id, aregulation) VALUES (?, ?)";
            for (String regulation : request.getRegulations()) {
                jdbcTemplate.update(regulationSql, eventId, regulation);
            }
            log.info("Inserted {} regulations for event {}", request.getRegulations().size(), eventId);
        }
        
        // 4. Insert Sessions and Ticket Categories
        for (SessionRequest sessionRequest : request.getSessions()) {
            Long sessionId = createSession(eventId, sessionRequest);
            
            // Insert ticket categories for this session
            for (TicketCategoryRequest ticketCategory : sessionRequest.getTicketCategories()) {
                createTicketCategory(eventId, sessionId, ticketCategory);
            }
        }
        
        log.info("Event creation completed successfully for event ID: {}", eventId);
        return eventId;
    }

    @Override
    @Transactional
    public Long createSession(Long eventId, SessionRequest sessionRequest) {
        log.debug("Creating session for event: {}", eventId);
        
        // Calculate max capacity from all ticket categories
        int maxCapacity = sessionRequest.getTicketCategories().stream()
                .mapToInt(TicketCategoryRequest::getQuantity)
                .sum();
        
        // Determine session type based on provided fields
        String sessionType = (sessionRequest.getVenueName() != null && !sessionRequest.getVenueName().isEmpty()) 
                            ? "OFFLINE" : "ONLINE";
        
        // 1. Insert into session table (session_id is auto-generated by IDENTITY)
        String sessionSql = "INSERT INTO [session] (event_id, start_date_time, end_date_time, " +
                           "max_capacity, type) VALUES (?, ?, ?, ?, ?)";

        KeyHolder keyHolder = new GeneratedKeyHolder();
        jdbcTemplate.update(connection -> {
            PreparedStatement ps = connection.prepareStatement(sessionSql, Statement.RETURN_GENERATED_KEYS);
            ps.setLong(1, eventId);
            ps.setTimestamp(2, Timestamp.valueOf(sessionRequest.getStartDateTime()));
            ps.setTimestamp(3, Timestamp.valueOf(sessionRequest.getEndDateTime()));
            ps.setInt(4, maxCapacity);
            ps.setString(5, sessionType);
            return ps;
        }, keyHolder);

        // Get the generated session_id
        Long generatedSessionId = keyHolder.getKey().longValue();

        // 2. Insert into specialized session table
        if ("OFFLINE".equals(sessionType)) {
            String offlineSql = "INSERT INTO offline_session (session_id, event_id, venue_name, venue_address) " +
                               "VALUES (?, ?, ?, ?)";
            jdbcTemplate.update(offlineSql,
                generatedSessionId,
                eventId,
                sessionRequest.getVenueName(),
                sessionRequest.getVenueAddress()
            );
            log.debug("Created offline session {} for event {}", generatedSessionId, eventId);
        } else {
            String onlineSql = "INSERT INTO online_session (session_id, event_id, meeting_url, platform_name) " +
                              "VALUES (?, ?, ?, ?)";
            jdbcTemplate.update(onlineSql,
                generatedSessionId,
                eventId,
                sessionRequest.getMeetingUrl(),
                sessionRequest.getPlatformName()
            );
            log.debug("Created online session {} for event {}", generatedSessionId, eventId);
        }
        
        return generatedSessionId;
    }

    @Override
    @Transactional
    public Long createTicketCategory(Long eventId, Long sessionId, TicketCategoryRequest ticketCategoryRequest) {
        log.debug("Creating ticket category: {} for session: {}, event: {}", 
                 ticketCategoryRequest.getCategoryName(), sessionId, eventId);
        
        // Use session start/end times for ticket sale period (can be customized later)
        String getSessionTimesSql = "SELECT start_date_time, end_date_time FROM [session] " +
                                   "WHERE session_id = ? AND event_id = ?";
        
        LocalDateTime[] sessionTimes = jdbcTemplate.queryForObject(getSessionTimesSql, 
            (rs, rowNum) -> new LocalDateTime[] {
                rs.getTimestamp("start_date_time").toLocalDateTime(),
                rs.getTimestamp("end_date_time").toLocalDateTime()
            },
            sessionId, eventId
        );
        
        // Calculate ticket sale period
        LocalDateTime now = LocalDateTime.now();
        LocalDateTime sessionStart = sessionTimes[0];

        // Ensure ticket sale end is after start (add at least 1 hour if session is too soon)
        final LocalDateTime ticketSaleStart = now;
        final LocalDateTime ticketSaleEnd = (sessionStart.isBefore(now) || sessionStart.isEqual(now))
                                            ? now.plusHours(1)
                                            : sessionStart;

        // Insert ticket category
        String ticketCategorySql = "INSERT INTO ticket_category (category_name, price, maximum_slot, " +
                                  "start_date_time, end_date_time, session_id, event_id) " +
                                  "VALUES (?, ?, ?, ?, ?, ?, ?)";

        KeyHolder ticketKeyHolder = new GeneratedKeyHolder();
        
        jdbcTemplate.update(connection -> {
            PreparedStatement ps = connection.prepareStatement(ticketCategorySql, Statement.RETURN_GENERATED_KEYS);
            ps.setString(1, ticketCategoryRequest.getCategoryName());
            ps.setBigDecimal(2, ticketCategoryRequest.getPrice());
            ps.setInt(3, ticketCategoryRequest.getQuantity());
            ps.setTimestamp(4, Timestamp.valueOf(ticketSaleStart));
            ps.setTimestamp(5, Timestamp.valueOf(ticketSaleEnd));
            ps.setLong(6, sessionId);
            ps.setLong(7, eventId);
            return ps;
        }, ticketKeyHolder);
        
        Long ticketCategoryId = ticketKeyHolder.getKey().longValue();
        log.debug("Created ticket category with ID: {}", ticketCategoryId);
        
        // Insert agreement terms if provided
        if (ticketCategoryRequest.getAgreementTerms() != null && 
            !ticketCategoryRequest.getAgreementTerms().isEmpty()) {
            String agreementSql = "INSERT INTO agreement_term (ticket_category_id, aterm) VALUES (?, ?)";
            for (String term : ticketCategoryRequest.getAgreementTerms()) {
                jdbcTemplate.update(agreementSql, ticketCategoryId, term);
            }
            log.debug("Inserted {} agreement terms for ticket category {}", 
                     ticketCategoryRequest.getAgreementTerms().size(), ticketCategoryId);
        }
        
        return ticketCategoryId;
    }
}
