package org.minhtrinh.eventease251.entity;

import jakarta.persistence.*;
import lombok.*;
import org.hibernate.annotations.GenericGenerator;
import org.minhtrinh.eventease251.ultility.OrganizerIdGenerator;
import org.minhtrinh.eventease251.ultility.StringSequenceIdGenerator;

@Entity
@Table(name = "organizer_profile")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@ToString(exclude = "user")
@EqualsAndHashCode(exclude = "user")
public class OrganizerProfile {
    @Id
    @GenericGenerator(
            name = "o_code_seq",
            type = OrganizerIdGenerator.class // <--- Point to your new class
    )
    @GeneratedValue(generator = "o_code_seq")
    @Column(name = "profile_code", length = 20)
    private String profileCode; // Auto-generated by DB: O1, O2, O3...

    @OneToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "user_id", unique = true, nullable = false)
    private User user;

    @Column(name = "official_name")
    private String officialName;

    @Column(name = "tax_id")
    private String taxId;

    @Column(name = "logo_url")
    private String logoUrl;

    @Enumerated(EnumType.STRING)
    @Column(name = "status")
    private OrganizerStatus status = OrganizerStatus.PENDING;
}

