package org.minhtrinh.eventease251.entity;

import jakarta.persistence.*;
import lombok.Data;

@Entity
@Table(name = "organizer_profile")
@Data
public class OrganizerProfile {
    @Id
    @Column(name = "profile_code", length = 20)
    private String profileCode; // Auto-generated by DB: O1, O2, O3...

    @OneToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "user_id", unique = true, nullable = false)
    private User user;

    @Column(name = "official_name")
    private String officialName;

    @Column(name = "tax_id")
    private String taxId;

    @Column(name = "logo_url")
    private String logoUrl;

    @Enumerated(EnumType.STRING)
    @Column(name = "status")
    private OrganizerStatus status = OrganizerStatus.PENDING;
}

