package org.minhtrinh.eventease251.entity;

import jakarta.persistence.*;
import lombok.Data;
import java.time.LocalDate;

@Entity
@Table(name = "participant_profile")
@Data
public class ParticipantProfile {
    @Id
    @Column(name = "profile_code", length = 20)
    private String profileCode; // Auto-generated by DB: P1, P2, P3...

    @OneToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "user_id", unique = true, nullable = false)
    private User user;

    @Column(name = "full_name")
    private String fullName;

    @Column(name = "phone_number")
    private String phoneNumber;

    @Column(name = "date_of_birth")
    private LocalDate dateOfBirth;

    @Column(name = "age", insertable = false, updatable = false)
    private Integer age; // Computed column in DB
}

